name: ReColorfulMap
version: '@version@'
main: cn.lunadeer.reColorfulMap.ReColorfulMap
api-version: '1.20'
load: STARTUP
folia-supported: true
commands:
  tomap:
    description: Convert image to map
    usage: /tomap <image url> [scale(default 1)]
    permission: recolorfulmap.tomap
  reloadColorfulMap:
    description: Reload ReColorfulMap configuration
    usage: /reloadColorfulMap
    permission: recolorfulmap.admin
  cleanColorfulMap:
    description: Clean invalid maps data
    usage: /cleanColorfulMap
    permission: recolorfulmap.admin
permissions:
  recolorfulmap.tomap:
    default: true
  recolorfulmap.admin:
    default: op
