name: Java CI-CD with Gradle

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: "Set up JDK 21"
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle
      - name: "Build with Gradle"
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew shadowJar
      - name: "Stage"
        run: |
          mkdir -p staging
          if ls build/libs/*.jar 1> /dev/null 2>&1; then
            mv build/libs/*.jar staging/
          else
            echo "No JAR files found"
            exit 1
          fi
      - name: "Extract Tag"
        id: tag
        run: |
          TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: "GitHub Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.TAG }}"
          prerelease: false
          files: |
            staging/*.jar
